version: '3.4'

services:
  server:
    image: sdpequinor/release-aware-api:1.12.1
    restart: unless-stopped
    command: /scripts/run-local-server.sh
    build:
      context:  ./server/
      dockerfile: Dockerfile
    env_file:
     - server.env
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/go/src/app/src
    environment:
      REPOSITORIES: |
        golang/go,
        nodejs/node,
        Leaflet/Leaflet,
        containous/traefik,
        grafana/grafana,
        axios/axios,
        vuejs/vue,
        d3/d3,
        torvalds/linux,
        Microsoft/vscode,
        git/git,
        tmux/tmux,
        jenkinsci/jenkins,
        weaveworks/flux,
        facebook/create-react-app,
        facebook/react,
        pallets/flask,
        styled-components/styled-components,
        graphql/graphql-js,
        ReactTraining/react-router,
        docker/docker-ce,
        docker/compose,
        Azure/AKS,
        Azure/aks-engine,
        derailed/k9s,
        kubernetes/kubernetes,
        graphql-python/flask-graphql,
        graphql-python/graphene,
        behave/behave,
        sqlalchemy/sqlalchemy,
        rust-lang/rust,
        elastic/elasticsearch,
        elastic/kibana,
        Microsoft/TypeScript,
        Homebrew/homebrew-cask,
        gatsbyjs/gatsby,
        python/cpython,
        facebook/jest,
        eslint/eslint,
        webpack/webpack
      HELM_REPOS: |
        gitlab/gitlab,
        flux/flux,
        jetstack/cert-manager,
        stable/oauth2-proxy
  client:
    image: sdpequinor/release-aware-web:1.9.1
    tty: true
    restart: unless-stopped
    build:
      context:  ./client/
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./client/src:/code/src
    environment:
      REFRESH_INTERVAL: '10000'
